### PR TITLE
Add instructions on how to use maws in code

### PR DESCRIPTION
**Pull request by april**

### CODE REVIEW

**Comment by gene1wood** [comment]
I'd say we shouldn't recommend people output boto syntax to be called in python by a subprocess, but instead show how running maws before your execute your python code sets up the environment (either through environment variables or awscli config) so python code natively works without any modification.

**Comment by gene1wood** [comment]
Heh whoops, too slow. =(

**Comment by gene1wood** [comment]
Also it looks like travis checks failed on this

**Comment by april** [comment]
It only failed because I merged it prior to the build completing. There's nothing in the README.md that would cause it to fail.

**Comment by gene1wood** [comment]
Travis checks failed because of #201

**Comment by april** [comment]
> I'd say we shouldn't recommend people output boto syntax to be called in python by a subprocess, but instead show how running maws before your execute your python code sets up the environment (either through environment variables or awscli config) so python code natively works without any modification.

I spent about two hours trying to make this work with just a single IDE (PyCharm), and it's a huge pain in the butt. IDEs generally aren't designed to allow you to run command-line preexecution hooks that pass environmental variables into your code. There's also no indication that the codes expired like on the command line.

With these pieces of code, it just works and will very occasionally pop up if it needs to.

**Comment by gene1wood** [comment]
> I spent about two hours trying to make this work with just a single IDE (PyCharm)

The way I do this in PyCharm is by going to the "Run Configuration" where you tell PyCharm what to run and adding to the "Environment variables" field the value `AWS_PROFILE=infosec-dev-MAWS-Admin` for example.

Selection_133

It's a one time config on a project and works well for me.

**Comment by april** [comment]
Sure, but that works with `boto` (and not with `node`, etc.) and it can be fiddly if you're switching between profiles. It also only works if your code uses a single profile, so you can't use it for cross-account work or the like unless you setup ACLs across accounts.

**Comment by gene1wood** [comment]
> Sure, but that works only with boto3 (and not with node, etc.)

**Comment by gene1wood** [comment]
> Sure, but that works only with boto3 (and not with node, etc.)

This environment variable setting in run configurations is present for me in all the Jetbrains IDEs (I use Webstorm for node) but maybe not in other IDEs.

> it can be fiddly if you're switching between profiles
> It also only works if your code uses a single profile, so you can't use it for cross-account work or the like unless you setup ACLs across accounts.

RIght, to change profiles/AWS accounts you'd need to change your run configuration, though if you're regularly running a project in multiple AWS accounts, you could setup two run configurations (something that I do normally unrelated to `maws`) and there's a drop down to choose which one when you run.

> Maybe we could update the README.md to say that it's not the ideal method?

I don't think we have to tell the user what's ideal, just call out that you can just use the builtin AWS SDK support for storing credentials in awscli config files and environment variables *or* you can modify your code to be `maws` specific and use the new `boto` output option.

> Does your code generate a stack trace once the session is expired?

Exactly, when the session expires, calls to AWS just fail within the IDE as AWS returns an error.

**Comment by april** [comment]
Sounds good, I'll update the docs on Monday.  :)

**Pull request merged**
